In [1]:
import requests
import pandas as pd
import time
import random
from bs4 import BeautifulSoup

In [2]:
Output = pd.DataFrame()

In [13]:
Localities = ['Rajarhat', 'New-Town','Haltu','Hiland-Park','E-M-Bypass','Barasat-Madhyamgram','Action-Area-1','Action-Area-2','Action-Area-3','Garia','BT-Road','Salt-Lake-City','Howrah','Behala','Joka','Dum-Dum','Ballygunge','Tollygunge','Mukundapur','Kasba','Jessore-Road','Narendrapur','Jadavpur','New-Alipore','Rajpur-Sonarpur','Barasat','Salt-Lake-City-Sector-5','Sodepur','Lake-Town','Baguiati','Behala-Chowrasta']
for loc in Localities:
    Data = {}
    s = random.randrange(5,20)
    time.sleep(s)
    URL = 'https://www.magicbricks.com/property-for-sale/residential-real-estate?proptype=Multistorey-Apartment,Builder-Floor-Apartment,Penthouse,Studio-Apartment&Locality='+loc+'&cityName=Kolkata'
    r = requests.get(URL)
    soup = BeautifulSoup(r.content, 'html.parser') 
    small = soup.findAll(class_='flex relative clearfix m-srp-card__container')
    for part in small:
        got = part.get_text().split()
        
        for i in range(len(got)):
    # Price
            if got[i]=='Cr':
                try:
                    Data['Price']=float(got[i-1])*10000000
                except ValueError:
                    pass
            elif got[i]=='Lac':
                Data['Price']=float(got[i-1])*100000
    # Area per Sqft
            if got[i]=='per':
                if got[i+1]=='sqft':
                    Data['Per_Sqft']=float(got[i-1])
                elif got[i+1]=='sqyrd':
                    Data['Per_Sqft']=float(got[i-1])*9
                elif got[i+1]=='sqm':
                    Data['Per_Sqft']=float(got[i-1])*10.7639
    # BHK
            if got[i]=='BHK':
                try:
                    Data['BHK']=int(got[i-1])
                except ValueError:
                    pass
    # Type of House:- Builder/Apartment
            if got[i]=='Apartment':
                Data['Type']='Apartment'
            elif got[i]=='Builder':
                Data['Type']='Builder_Floor'
    # Area
            if got[i]=='super' or got[i]=='carpet':
                if got[i+3]=='sqft':
                    Data['Area']=int(got[i+2])
                elif got[i+3]=='sqyrd':
                    Data['Area']=int(got[i+2])*9
                elif got[i+3]=='sqm':
                    Data['Area']=int(got[i+2])*10.7639
    # Status
            if got[i]=='status':
                if got[i+1]=='Ready':
                    Data['Status']='Ready_to_move'
                elif got[i+1]=='Possession':
                    Data['Status']='Almost_ready'
    # Transaction
            if got[i]=='transaction':
                if got[i+1]=='New':
                    Data['Transaction']='New_Property'
                elif got[i+1]=='Resale':
                    Data['Transaction']='Resale'
    # Furnishing
            if got[i]=='furnishing':
                if got[i+1]=='Unfurnished':
                    Data['Furnishing']='Unfurnished'
                elif got[i+1]=='Furnished':
                    Data['Furnishing']='Furnished' 
                elif got[i+1]=='Semi-Furnished':
                    Data['Furnishing']='Semi-Furnished' 
    # Parking
            if got[i]=='parking':
                try:
                    Data['Parking']=int(got[i+1])
                except ValueError:
                    pass
    # Locality
            if got[i]=='in':
                j=i+1
                string =got[j]
                j+=1
                while(j<len(got)):
                    if got[j]=="What's":
                        break
                    else :
                        string +=(' '+got[j])
                    j+=1
                Data['Locality']=string
        
        
    # Bathroom
            if got[i]=='bathroom':
                try:
                    Data['Bathroom']=int(float(got[i+1]))
                except ValueError:
                    pass

                break
                
        
        Output = Output.append(Data,ignore_index=True)
    
    print(r.status_code)

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

In [14]:
Output

,Area,BHK,Bathroom,Furnishing,Locality,Price,Status,Transaction,Type,Per_Sqft,Parking
0,689.0,2.0,2.0,Unfurnished,"Orchard Avaasa, Rajarhat carpet area 689 sqft ...",4970000.0,Almost_ready,New_Property,Apartment,NaN,NaN
1,1165.0,3.0,2.0,Unfurnished,"Meena Aurum, Gouranganagar super area 1165 sqf...",3840000.0,Ready_to_move,New_Property,Apartment,3100.0,NaN
2,3770.0,3.0,3.0,Unfurnished,"Dream One, New Town super area 3770 sqft statu...",21400000.0,Almost_ready,New_Property,Apartment,5695.0,NaN
3,1680.0,4.0,3.0,Unfurnished,"Ascon Era, Rajarhat super area 1680 sqft statu...",8730000.0,Almost_ready,New_Property,Apartment,5199.0,1.0
4,1970.0,3.0,3.0,Unfurnished,"The Orchid Grandeur, Rajarhat super area 1970 ...",7000000.0,Ready_to_move,New_Property,Apartment,3553.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2662,750.0,2.0,2.0,Unfurnished,Behala Chowrasta carpet area 750 sqft status R...,2600000.0,Ready_to_move,New_Property,Apartment,4692.0,1.0
2663,870.0,3.0,2.0,Semi-Furnished,Behala Chowrasta carpet area 870 sqft status P...,4200000.0,Almost_ready,New_Property,Apartment,4692.0,2.0
2664,1110.0,3.0,2.0,Unfurnished,"Greenfield City, Behala Chowrasta super area 1...",4350000.0,Ready_to_move,Resale,Apartment,3918.0,1.0
2665,677.0,3.0,2.0,Unfurnished,Behala Chowrasta carpet area 677 sqft status P...,4760000.0,Almost_ready,New_Property,Apartment,3918.0,1.0
2666,801.0,3.0,3.0,Unfurnished,"Next, Behala Chowrasta carpet area 801 sqft st...",5970000.0,Almost_ready,New_Property,Apartment,3918.0,1.0

In [17]:
Output.to_csv('Kolkata_housing_data_magicbricks.csv')